### ISSUE TITLE
Estilos en reveal

### ISSUE THREAD

**Issue by hhkaos** [asanzdiego/markdownslides#2]
Hi crack!

He estado probando el proyecto y me ha gustado mucho!, de hecho creo que lo voy a usar para hacer las slides del curso de Introducción a HTML5 que estoy haciendo con Gitbook :) (aprovechando que los textos los tengo ya en Markdown también :D).

Una pregunta/sugerencia, he visto que reveal [tiene varios estilos](http://lab.hakim.se/reveal-js/#/themes), entonces la pregunta es, además del estilo *League*, se podría elegir el estilo en el que queremos que nos genere las slides/pdfs?

Por cierto para Mac funciona, pero hay que instalar el [BasicTeX](https://tug.org/mactex/morepackages.html) y configurarlo en el PATH, en mi caso:

```bash
#!/bin/bash
PATH=$PATH:/usr/local/texlive/2015basic/bin/universal-darwin/
```

Otra pregunta, al generar el HTML, el *pre* del código me sale sin resaltar el código (le he puesto a mano Bootstrap):

<img width="1182" alt="screenshot 2016-01-03 20 20 21" src="https://cloud.githubusercontent.com/assets/826965/12080327/77a86e1c-b257-11e5-9e32-7efbdc908100.png">

¿Sabes cómo se puede estilar sin tener que tocar el código?

Thx crack!, 1 abrazo!

**Comment by asanzdiego** [comment]
Hola:

Me alegro de que lo vayas a usar: todo un honor para mi :)

Te contesto por partes:

# Gitbook

Mi idea original, era tener el mismo archivo Markdown para los apuntes y para las slides. ¿Cómo? Añadiendo algún tipo de marcaje para dejar "notas" para los apuntes que no se vieran en las slides. Pero eso todavía no lo he implementado.

Lo que si que he implementado son los subniveles: cuando exportas a modo libro (HTML, DOCX u ODT) se quedan todos los subniveles, que en las slides se reducen a sólo 2 (slides de título para el nivel superior, y slide normal para el resto)

# Remark

Relacionado con lo anterior, en un futuro no muy lejano, me gustaría que exportase también a [remark](http://remarkjs.com/) que la verdad son unas slides muy chulas, sobre todo porque admite notas, y modo presentación.

![Remark admite notas y modo presentación](https://cloud.githubusercontent.com/assets/1641592/12100234/037f6f0e-b32e-11e5-8915-ac08ba644b5f.png)

# Estilos

Tanto reveal, como deck, admiten distintos estilos. Esto se puede configurar en las [plantillas](https://github.com/asanzdiego/markdownslides/tree/master/templates). Como verás tengo 2 plantillas para reveal y 2 para deck. La única diferencia de las 2 plantillas es el CSS utilizado. Una planatilla tiene el CSS "normal" y otra tiene un CSS alternativo con fondo blanco. Cambiando la plantilla, puedes poner el CSS que te apetezca.

# Pre

Puedes darle color al código siplemente añadiendo el lenguaje que estas utilizando:

ejemplo:

\~\~\~javascript
function hola() {
&nbsp;&nbsp;&nbsp;&nbsp;return "Hola Mundo";
}
\~\~\~

~~~javascript
function hola() {
    return "Hola Mundo";
}
~~~

Ver: [Pandoc fenced code blocks](http://pandoc.org/README.html#fenced-code-blocks)
