### ISSUE TITLE
Imagenes remotas por https

### ISSUE THREAD

**Issue by cesarseoane** [asanzdiego/markdownslides#5]
Hola Adolfo.

Gracias por este proyecto. No conocía MarkDown, y me parece fenomenal poder preocuparme solo del contenido de las presentaciones mientras las preparo. Me encanta este proyecto!! Y lo mejor es que a los alumnos también!!

**He comprobado que cuando añades imágenes a la presentación desde urls externas a la presentación**

ej 

`![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/USB3.0_connectors.svg/250px-USB3.0_connectors.svg.png)`

si la url es por https, cuando se exporta a pdf, algunas, no las incluye en la presentación.

Se puede solucionar añadiendo el parámetro --ssl-protocol=any  en la llamada de phantomjs. (Consultar en http://phantomjs.org/api/command-line.html)

Por defecto el valor de ssl-protocol es sslv3, y no aceptará ninguno de los otros valores. Parece que las imágenes de Wikipedia no encajan con sslv3

Consideras que apropiado modificar a any el requerimiento de certificado ssl? Crearé una Pull Request para que lo puedas aplicar si tu quieres.

Gracias por este proyecto ;))

**Comment by asanzdiego** [comment]
Gracias @cesarseoane por tu aportación y por [tu pull-request que arregla el problema](https://github.com/asanzdiego/markdownslides/pull/6).

Un saludo.

**Comment by cesarseoane** [comment]
Solo una gotita de colaboración para esta gran APP. Muchas gracias Adolfo, me resulta muy útil en mis clases
